library(readr)
library(dplyr)
library(rDEA)
Data <- read_csv("Data.csv")
head(Data)
in_var <- select(Data, "OPERATING EXPENSE")
out_var <- select(Data, "PROFIT AFTER TAX")
Constant2Scale_Model <- dea(XREF = in_var, YREF = out_var, X=in_var, Y=out_var, model = "input", RTS = "constant")
Variable2Scale_Model <- dea(XREF = in_var, YREF = out_var, X=in_var, Y=out_var, model = "input", RTS = "variable")
result1 <- cbind(round(Constant2Scale_Model$thetaOpt,4))
rownames(result1) <- Data[[1]]
colnames(result1) <- c("Efficiency")
View(result1)
result2 <- cbind(round(Variable2Scale_Model$thetaOpt,4))
rownames(result2) <- Data[[1]]
colnames(result2) <- c("Efficiency")
View(result2)
